### ISSUE TITLE
Rate Limiting

### ISSUE THREAD

**Issue by DheekshuKumar** [CovEducation/CovEd#108]
People should not be able to request more than 4 mentors every 48 hours.

**Comment by oupadhyay** [comment]
This would be a change to the time limits that were made in #16 and #39. Why is this labeled a bug? I think you can try to contact a mentor multiple times, but the max we have is 4 times (I have yet to go back and see, but this is what I remember).

**Comment by johancc** [comment]
The rate limiting is bypassed when users use multiple devices / IP addresses I believe. There was an instance of a user requesting way too many mentors over 3 days. The way to fix this would be to store the last time they requested a mentor and doing the limiting on the server side.
