### ISSUE TITLE
Add Redirect after Parent Acknowledgement Page

### ISSUE THREAD

**Issue by sanjayyepuri** [CovEducation/CovEd#134]
Currently after a parent signs a student up, we redirect the parent to the `/parentacknowledgement`.  There is no acknowledgement button or any other actionable on this page; it is not clear to parents which page to visit next. 

We would like to add a button to ParentAcknowledgement.js that verifies that the parent has seen the message and redirects them to`/findamentor` upon being clicked. We also want to disable/hide the other navigation buttons to other pages when on ParentAcknowledgement so that parents must click on the "accept" button.

**Comment by oupadhyay** [comment]
Can we make the `/parentacknowledgement` a **pop-up message**? This way, it will block all other navigation buttons without really creating a new environment. Moreover, it will be like the `Terms of Service` or `Privacy Policy` notices that websites make you go through and then have you agree to the predatory terms of service that almost always sell your data.  :disappointed:
