### ISSUE TITLE
Automatic Safety Check mentor name

### ISSUE THREAD

**Issue by DheekshuKumar** [CovEducation/CovEd#72]
look into automatically checking name in sex offender registry

**Comment by johancc** [comment]
After a brief search I found this one https://www.familywatchdog.us/APIHow.asp. It's not free however

**Comment by kat-y** [comment]
from Richard in pr channel: "The suggestion I got from Jumpstart which is an Americorps org was to just enter a name into the search of https://www.nsopw.gov/"
