### ISSUE TITLE
UI of student messaging

### ISSUE THREAD

**Issue by kat-y** [CovEducation/CovEd#82]
"Student sign up: I feel like students might send multiple messages to one student since the message box is still there after they submit a message and the only thing that changes is the arrow turns to a green checkbox"

(from bash feedback)

**Comment by DheekshuKumar** [comment]
so basically, upon sending, we want to close the modal yes?

**Comment by kat-y** [comment]
Do we want to close the modal? (what if students accidentally send before they're finished?)
