### ISSUE TITLE
mentors with @mit.edu emails not getting verification emails

### ISSUE THREAD

**Issue by kat-y** [CovEducation/CovEd#85]
Seems like other mentors are able to get verifed, but mentors with @mit.edu emails have not gotten verification emails. 

https://ist.mit.edu/spam says even if it's marked as spam it will be delivered to the Gmails we have forwarding set up with, and it's not in Gmail spam or anywhere else.  

Mentors are still listed and can be contacted by mentees

**Comment by johancc** [comment]
I think that forwarding has some delay. I got the verification email fairly quickly, but I would wait a couple minutes then it should appear.

**Comment by kat-y** [comment]
interesting, it's been several hours and both me and another person still haven't received it.

**Comment by kat-y** [comment]
closed for now, but seems like the time to receive verification email varies a lot
