### ISSUE TITLE
student account profile requires student email

### ISSUE THREAD

**Issue by kat-y** [CovEducation/CovEd#92]
related but different from #80 , when editing the profile of a student account you must put in student email (though it says 'Student Email (Optional)"

**Comment by sanjayyepuri** [comment]
https://github.com/CovEducation/CovEd/blob/b1ca5d4bccebfcf2099e420f8e27a0c371ea809d/client/src/components/pages/Profile.js#L59-L64

I think this is the issue in the schema causing the error. To fix this, I believe you can move the error message from required to the email call `email("...")` and remove lines 61-63.
